version: '3.8'
services:
  freeswitch:
    image: signalwire/freeswitch:latest
    container_name: freecall-freeswitch
    restart: unless-stopped
    ports:
      - "5060:5060/udp"
      - "5080:5080/udp"
      - "8021:8021"
      - "16384-32768:16384-32768/udp"
    volumes:
      - ./freeswitch/conf/autoload_configs/event_socket.conf.xml:/etc/freeswitch/autoload_configs/event_socket.conf.xml
      - ./freeswitch/conf/dialplan/default/00_freecall.xml:/etc/freeswitch/dialplan/default/00_freecall.xml
